---
 - name: Create a Directory
   hosts: workers
   become: yes
   tasks:
    - name: Create a Directory
      ansible.builtin.file:
       path: /home/ec2-user/tanvitha
       owner: ec2-user
       group: ec2-user
       mode: 0755
       state: directory
