
---
 - name: Delete a file inside /home/ganesh/ansible/misc-ansible/father
   hosts: servers
   become: yes
   tasks:
    - name: Deleate a file
      ansible.builtin.file:
       path: /home/ganesh/ansible/misc_ansible/father/ganesh.txt
       owner: ganesh
       group: ganesh
       state: absent

